---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math28-postgresql
  namespace: math28
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math28-postgresql
  template:
    metadata:
      labels:
        app: math28-postgresql
    spec:
      containers:
      - name: math28-postgresql
        image: postgres:17
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: Phetolo.Math28DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: math28-postgresql-pvc  
---
apiVersion: v1
kind: Service
metadata:
  name: math28-postgresql
  namespace: math28
spec:
  type: ClusterIP
  selector:
    app: math28-postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432 