name: Build Angular App

on:
   push:
     branches: [ main ]

jobs:
   build-angular:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - name: Setup Node JS
         uses: actions/setup-node@v6.0.0
         with: 
            node-version: 24.x

       - name: Install dependencies
         run:  cd AngularWeb && npm install

       - name: Build
         run: cd AngularWeb && npm run build

       - name: Unit Tests
         run: cd AngularWeb && npm run test:ci



