name: Deploy Angular App

on:
    [workflow_dispatch]

jobs:
   deploy-angular:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - name: build docker image
         run: docker build ./AngularWeb/ -t kgapzajedi56/math28.angularapp:latest

       - name: push image to docker hub
         run: |
           docker login -u kgapzajedi56 -p ${{secrets.DOCKER_HUB_TOKEN}}
           docker push kgapzajedi56/math28.angularapp:latest
